# Generated by Django 3.2.4 on 2021-08-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_auto_20210812_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('contactNo', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
