# Generated by Django 3.2.4 on 2021-08-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_docotor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docotor',
            new_name='Doctor',
        ),
    ]
